### ISSUE TITLE
Message "Configuration file: [...]/_config.yml" repeated over and over in console

### ISSUE THREAD

**Issue by AxelTerizaki** [avillafiorita/jekyll-datapage_gen#50] opened 2018-09-13 14:22 UTC
When generating a website using this plugin, my console gets flooded with this message (I removed the full path from it)

I'm not too sure what triggers it, wether it's the collection itself, or if it's the `datapage_url` liquid filter provided by the plugin (BTW I discovered it by chance, it's not in the docs IIRC). I use the filter a lot due to how it allows me to link generated pages from other pages.

You can take a look at the jekyll site in question if you want to try it out : https://lab.shelter.moe/karaokemugen/sites/mugen-site

This is not a particularly big bug but it's kind of annoying :)

**Comment by avillafiorita** [comment] 2018-10-12 13:55
Hi there, could you send me your configuration file, to understand where the problem is?

**Comment by avillafiorita** [comment] 2018-10-16 14:06
Never mind, I observed the behavior when trying to reproduce issue 54. "Upgrading" it to bug

**Comment by kencoenen** [comment] 2019-08-21 09:46
This can be fixed by changing `Jekyll.configuration({})['page_gen-dirs']` into `@context.registers[:site].config['page_gen-dirs']`.

**Comment by jeremydouglass** [comment] 2019-08-21 15:04
I'm also seeing this problem in Jekyll 3.5.2.

I'm guessing the fix that @kencoenen suggests would go here?

https://github.com/avillafiorita/jekyll-datapage_gen/blob/e4351d5710c97fb99a0362ce2e9a4e5b2ad12fe0/data_page_generator.rb#L128

**Comment by dannguyen** [comment] 2020-03-17 14:23
Just wanted to say big thanks to @kencoenen for creating  and naming this issue so that it was easy to find a year later :)

The code substitution works just as ken and @jeremydouglass say, within the definition of `datapage_url()` in `data_page_generator.rb`

```rb
    def datapage_url(input, dir)
# OLD    extension = Jekyll.configuration({})['page_gen-dirs'] ? '/' : '.html'
# NEW   change via: https://github.com/avillafiorita/jekyll-datapage_gen/issues/50#issuecomment-523383573
      extension = @context.registers[:site].config['page_gen-dirs'] ? '/' : '.html'
      "#{dir}/#{sanitize_filename(input)}#{extension}"
    end
  end
```

**Comment by avillafiorita** [comment] 2020-04-16 10:26
I have finally introduced the changed suggested by @kencoenen. 

49 chars changed in 240 days: this estimates my productivity at 4 days per char... it does not include the time to delete the old line, though ;-)

Thanks to everyone for their patience and to @kencoenen for providing the solution!

**Closed by avillafiorita** 2020-04-16 10:26 UTC
Labels: bug, enhancement
